name: roadcarsapp
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.20
  intl: ^0.17.0
  font_awesome_flutter: ^10.1.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.2
  image_picker: ^1.1.2
  cloud_firestore: ^5.4.3
  image_picker_for_web: ^3.0.5
  google_sign_in: ^5.0.7
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  dotted_border: ^2.1.0
  flutter_svg: ^2.0.10+1
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.16
  flutter_form_builder: ^7.0.0

flutter_native_splash:
  color: "#000000"
  image: "assets/app/splash.png"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/app/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/app/icon-android.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/app/
