// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhRHb2aO63ZazUdnfSeP8Xi7EJPTf-UMk',
    appId: '1:1056284825768:web:bf457a3635d6ad3fdb4a9d',
    messagingSenderId: '1056284825768',
    projectId: 'roadcarsapp',
    authDomain: 'roadcarsapp.firebaseapp.com',
    storageBucket: 'roadcarsapp.appspot.com',
    measurementId: 'G-X2L8FJE9Q2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIYXgOPkuPw77vjCVmNtqAELqUNVd2D7E',
    appId: '1:1056284825768:android:3b3297f8df94fad8db4a9d',
    messagingSenderId: '1056284825768',
    projectId: 'roadcarsapp',
    storageBucket: 'roadcarsapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKxy4mDbDpJzBSGpuaEFE4oVdHsE01qj8',
    appId: '1:1056284825768:ios:e415bac993ef12f6db4a9d',
    messagingSenderId: '1056284825768',
    projectId: 'roadcarsapp',
    storageBucket: 'roadcarsapp.appspot.com',
    iosClientId: '1056284825768-emt2e1cg9dn1kpuukhne5vgdm7c3ee0m.apps.googleusercontent.com',
    iosBundleId: 'com.example.roadcarsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKxy4mDbDpJzBSGpuaEFE4oVdHsE01qj8',
    appId: '1:1056284825768:ios:e415bac993ef12f6db4a9d',
    messagingSenderId: '1056284825768',
    projectId: 'roadcarsapp',
    storageBucket: 'roadcarsapp.appspot.com',
    iosClientId: '1056284825768-emt2e1cg9dn1kpuukhne5vgdm7c3ee0m.apps.googleusercontent.com',
    iosBundleId: 'com.example.roadcarsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhRHb2aO63ZazUdnfSeP8Xi7EJPTf-UMk',
    appId: '1:1056284825768:web:95a979a5930addc3db4a9d',
    messagingSenderId: '1056284825768',
    projectId: 'roadcarsapp',
    authDomain: 'roadcarsapp.firebaseapp.com',
    storageBucket: 'roadcarsapp.appspot.com',
    measurementId: 'G-CERDHDQKP7',
  );
}
